---
distro: bionic
language: generic
install: true

jobs:
  include:
    - name: Linux AMD64 OpenJDK8
      env: JDK_VERSION=8
    - name: Linux AMD64 OpenJDK11
      env: JDK_VERSION=11
    - name: Linux ARM64 OpenJDK11
      arch: arm64
      env: JDK_VERSION=11
    - name: MacOS OpenJDK8
      os: osx
      env: JDK_VERSION=8

before_install:
  - if [[ ${TRAVIS_OS_NAME} = "linux" ]]; then sudo apt update -y; sudo apt install openjdk-${JDK_VERSION}-jdk; fi
  - if [[ ${TRAVIS_OS_NAME} = "osx" ]]; then brew update; brew install openjdk@${JDK_VERSION}; fi

script: ./mvnw test -Ptravis

notifications:
  email:
    - michael@mosmann.de

cache:
  directories:
    - $HOME/.m2/repository
